apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  template "name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{  template "name" . }}
    app.kubernetes.io/name: {{  template "name" . }}
    app.kubernetes.io/instance: {{  template "name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{  template "name" . }}
      app.kubernetes.io/name: {{  template "name" . }}
      app.kubernetes.io/instance: {{  template "name" . }}
  template:
    metadata:
      labels:
        app: {{  template "name" . }}
        app.kubernetes.io/name: {{  template "name" . }}
        app.kubernetes.io/instance: {{  template "name" . }}
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9402'
    spec:
      serviceAccountName: {{  template "name" . }}
      containers:
        - name: {{  template "name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          #image: "quay.io/jetstack/cert-manager-controller:v0.13.1"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --v=2
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace=kube-system
          - --webhook-namespace=$(POD_NAMESPACE)
          - --webhook-ca-secret=cert-manager-webhook-ca
          - --webhook-serving-secret=cert-manager-webhook-tls
          - --webhook-dns-names=cert-manager-webhook,cert-manager-webhook.cert-manager,cert-manager-webhook.cert-manager.svc
          ports:
          - containerPort: 9402
            protocol: TCP
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  template "name" . }}-cainjector
  namespace: {{ .Values.namespace }}
  labels:
    app: {{  template "name" . }}-cainjector
    app.kubernetes.io/name: {{  template "name" . }}-cainjector
    app.kubernetes.io/instance: {{  template "name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{  template "name" . }}-cainjector
      app.kubernetes.io/name: {{  template "name" . }}-cainjector
      app.kubernetes.io/instance: {{  template "name" . }}
  template:
    metadata:
      labels:
        app: {{  template "name" . }}-cainjector
        app.kubernetes.io/name: {{  template "name" . }}-cainjector
        app.kubernetes.io/instance: {{  template "name" . }}
      annotations:
    spec:
      serviceAccountName: {{  template "name" . }}-cainjector
      containers:
        - name: {{  template "name" . }}
          image: {{ .Values.cainjector.image.repository }}:{{ .Values.cainjector.image.tag }}
          imagePullPolicy: {{ .Values.cainjector.image.pullPolicy }}
          args:
          - --v=2
          - --leader-election-namespace=kube-system
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {}
            
---          