{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{  template "name" . }}-cainjector
  namespace: {{ .Values.namespace }}
  labels:
    app: {{  template "name" . }}-cainjector
    app.kubernetes.io/name: {{  template "name" . }}-cainjector
    app.kubernetes.io/instance: {{  template "name" . }}
---
# Source: cert-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{  template "name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
  labels:
    app: {{  template "name" . }}
    app.kubernetes.io/name: {{  template "name" . }}
    app.kubernetes.io/instance: {{  template "name" . }}
---
{{- end -}}
