cluster-configs:
    secrets:
        db:
            username: egovdbuser    #local DB cred
            password: postgres@4321
            flywayUsername: egovdbuser
            flywayPassword: postgres@4321
        egov-enc-service:            # use-enc keys to encrypt/decrypt users details
            master-password: keiz0phashiNgoh7
            master-salt: Eegh8ut7
            master-initialvector: quooR4Oereiy 
        egov-location:                # google maps key 
            gmapskey: AIzaSyADqpKqZOggMr33usQvZ5hml3tyWZ6SCMc       
        git-sync:     # Read-only user
            ssh: |
                -----BEGIN RSA PRIVATE KEY-----
                MIIJKQIBAAKCAgEAxN3yoWfXEl7227hAXUTpeN5SiGUe22sIlGSYk3fx2Zl1xW0t
                B5Y/RfxG3KocwtGCmxq+eMur9ZZsP5B8qFguG1ZhJXRZrFTn8S6bmVSP1YBRv93O
                wvGNiLrSkqeKTbAflj/347aGOyO6tG+lDFPtGDOWI8EXQNRDKQb7zxans9fdli1u
                vdXEDEF5nqzso0CLOtWjnRcOdWOghOyKdHZLvDIqwMSDvOVcnWH/zUqjMqpQJItu
                bCun9tvRGxU5eSdTXCR7bs5qvm0NJR2VdJFZJNnxy9i0iQrinpLNlmoWl0LEunns
                vSI9nBd3s0/l0nVzNzyvstCnywR8BKj1QxbkYArtkEY/1kLkmjEo7KO9ahHOI5qG
                Tx9oJsBVAtHfO5Q3q4laEmbl9t1UE7XSp/0RD4+jqSlVS4q/Z3+MLHKfNu3Pps4A
                Zq1WmaMch5NxB9qo1zj6x7LENVkzX29urHhlOnhJKZG8A/2Iz6rqzZTwV5g1kxSJ
                dbfLg7K++zgyaJzluchWo5KCidC2icORklwvdnoDpu6qKD7hZBf4LscIV36Mwr79
                z+EvTCrkaKjUTQMdc+mgzwRldHWgwRTZjkEIX13v8r5x9Pl1JuIttONhINurN3dn
                woKGb9rFFfBaLqEMU7VAHZ20SO0E4na7b4v2nOwWixcOezIwYVl6V3zN6IcCAwEA
                AQKCAgAFUqr4ykH6cS7jifvTicV2SyyYG4PWEvLMcFvfwOJ9K7UPfYA2ME3NqqCP
                3tmgOuH5J6P2yCsCHOsYXOPB+YBlpNRDmv3Btxn+X3A9mRe6ghmzwl+Qzc8x3ztK
                U9VdfGGeQmSFd63xc2nc7xfbWXmTqfFpThM+4X5fYZz1YHtwVWncYaYY4+rFGhAb
                xjkvwNMC6DvgR3tQmT0B2xNzSq+JiyG0zJtzRBBZAQlVl6sJ96jrFAoMSrHj7tWc
                kdpX+EQ8vY/I0zP3qiMs2bvsxvFOGcZ76IQZIH44I2gDpSKvPFLtZ9aK1p4r1kaa
                RpLEOgC/gZiOkS24Q4rG5XqcMcZC9mMlWHqUJGhYrZhEn0yCQEtQFwiaDbuwQ+eA
                1RJ4Lxm9sGFuM1TuqU+1hLNc2/alZtclq2R424yCjzkz00vPNF+TpOGDdlUMiLpe
                2kbgYyY/hXKrSl2dbWPe00bj0AfNhdDJgb8cDVf9lz/MniG3A/U2St4lKK4ULDgt
                /BRwLJzYROP/p1NWNO3m18BvJRXt16dAsBAXy+49CVY+t3twZ4KNO+hzOC+T2bXs
                RZWWZXBsSXcT8suCy8CpzsM2V6wmipjBEcTR8MOjBHa5XSSH/e7k4+c1mV2Kjdix
                5GHNEi/oYgseBlIo5SeDtgcVRRX8L07ttG7LjuKW2icrcQnWgQKCAQEA6AFeRdO4
                ajHavP9t9DZEQWs0Xl0xsa4E0BTOXCGvxOgr9mg5ZaVzy/O53aaT92Geb5LkWhJJ
                5STLLEl7C+7WDn4Tn4EOqS2BQVylzjuP7/5ljSuH2rNl45r2t88HU+PT6hhW1xw9
                UyNZ2dqITAHIGSpZLosjsb1i5GPcgxkNrRYBH96Zew9GQ87yIu9cI5FpQSA1ijiu
                6B9AozIGAkEBgHj98RgO16Wh6f9UsAyWgiyq67IP3f1cexzuH6sgPWFjvUv4+F7i
                HDMZmtftA3sDfs4hFhe7PW0WcW/Ys2ucfjDVeqlOZrlLbDoUYEHZwb3/Ts+Xs5F5
                tRNtpKIPNrFvVwKCAQEA2To/WNk+7pZGZZQU/xyYHiyO9979TtkMnaXOF6Wr8bSD
                UAm+4+fPBg3iKhqEOlf8Ldrz1Cc7boIJATx5RmFs+zuc8H9LU0GHp9S/AQ7xjmcG
                Os6QmPI2dyQ5dFeKt1eRqZhcedAO1bsj3idnrbk64mfwfxFi86xX80oLBabmDba+
                w5cqjOfGHMfXiHebtUiuOLrxM8no3bAVpf9chzZODdSsLZT6J8Lep4A9pnPsYw+9
                vU1QgTYqk7sTL2ZTA963nm5IACrPBg866p98MRsdlagXtasduWBwnXNTnqM8nKX0
                /Wf90KtbN+ueep8/qWPF4QRZL/wj6y11nyvYIq0CUQKCAQA6dQXM8FDaKR+lWXLa
                AsZl+V4jnLXFwEQkLenlGvPP2HQjTRWRQAQSUqH1cGB+B5HFKSzyaQNHgmLTENy5
                H/+9fRTyrrED/ZxA3NhGQ4m7/cyWqm47s9IrbENYAwkkoRYnOOTApLPq+9BK7R5E
                kHpbpOj9qj9fLIn7ZBIO0kQ45X95CTyA3lNlCILIPKlpqNztdPEol6mygRVnSVZs
                QPbg6RuLIPW0bl6CuDwdc76EpD6Yzq/izlD8EEkLn7Gq5Zwc+USNSFMOqe18r4Vf
                yCIUVFnP2EDsdE0gXf8rDiVLQoC3vGstxOh1J5k0u8LjZz0qHXJq42/YKUIKJm9Q
                55pXAoIBAQCGgkfZd2Q9jnX2zjQWKBmVjZfVqpGFsmbac2HjSKXo3BL3i6FVNCQA
                JralxZedHQA9ULfs5YIqkoCK8GxUBV3bT3WFgf0dh5U9ekHvoNY4jFjSLzhgTJMn
                QRoGjXKKxsGel4ajsw6Mj/3MwO+1Jd5tdVj5BcYVBuHK901N6aPIWCFVsZQafiYx
                ihlPGmkjXubqn+9dVyhHpZIyIKal3x2D+O3Ip9giqMsAQytpl5yHVqbxwh8Yc3b3
                1T4y+pRq8A0ZIEabO+bHZMThpXHcYmL2WYic6GFWeX4iMNhVgdS1VxoVk8AZ5xFr
                1g1i9psQA4TzKaMkUGfZZ2PO9PI3vpORAoIBAQDJOh5OWRFZCgHwMTOumgxv/wof
                CuhsAzJ4tQZ0kMWGMXh1JuBgnLOWn6SgNLhl1SErwx67ftNhfFIXJR7WkNJ7n8Oe
                DY9NZtgq85Lm/THmdn07COFrQpDzhZIy0YYHc3EZL0EjOOz0vrYOJAnWphAdSbYt
                P//GtFAuNQ6HYEX48XUJ3NgBzBbweS03jEQBdE1CiH4GIxqT1BEr+OgHjyCEynLA
                z9biV2jCYKO6W2CsxsjVGqvEFkOcGz3OwPFQGYEM85W5piKKZnP8LoElIhpZ82gF
                ZN2SXKC6SZumRAcRdloo5jq5Qg0JDo+ltxHLeyTU/eJyY7aIojsWHm5kUlbf
                -----END RSA PRIVATE KEY-----
            known-hosts: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
